### PR TITLE
Attendance

### PR DESCRIPTION
**Pull request by GhaidaMomani**

### CODE REVIEW

**Review by makkahwi — COMMENTED** [review]
Nice, but you didn't import model in app/models/__init__.py

**Comment by makkahwi** [comment]
You also need to add the permissions to your views. For now, could do it like Yahya showed us, isOwnerOrReadOnly

**Review by makkahwi — COMMENTED** [review]
In Attendance model, you're saving the student name n student foreign key. No need for the name, foreign key is to bring all student data from students table of DB. 

Also, you forgot to make a property for attendance taking. It's student details & timestamps. Where is the key to save the indicator that student attended or was absent

**Comment by GhaidaMomani** [comment]
Thank you Suhaib for your notes 
Most of the features of the attendance part needs to be discussed in a front-end manner which we will do in before the merge party.

**Pull request closed without merging**
