### PR TITLE
Student_experience_forum

### PR DESCRIPTION
**Pull request by moayadabukhadra**

### CODE REVIEW

**Review by makkahwi — COMMENTED** [review]
Nice, but again you forgot timestamp & updated properties in the model. You also didn't import model in app/models/__init__.py

**Comment by makkahwi** [comment]
You also need to add the permissions to your views. For now, could do it like Yahya showed us, isOwnerOrReadOnly

**Review by makkahwi — COMMENTED** [review]
Btw, in almost all your codes, you are defining company name & details. There is no need for that, There is a user model for the company of which have all the details. Please please revisit your works n repalce company name & details with forignkey like you did with student data.

**Comment by moayadabukhadra** [comment]
> Btw, in almost all your codes, you are defining company name & details. There is no need for that, There is a user model for the company of which have all the details. Please please revisit your works n repalce company name & details with forignkey like you did with student data.

**Review by makkahwi — APPROVED** [review]
Nice

**Pull request merged**
